### ISSUE TITLE
다른 사용자들 리뷰

### ISSUE THREAD

**Issue by PMinJoo** [ProjectInTheClass/MovieDialog#18]
https://docs.google.com/presentation/d/1oFBqnCZjykwpmwaQiOG-lxMq4RYz16pe_P7gGP1P7yY/edit?usp=sharing

**Comment by IMCHO** [comment]
첫화면을 전체보기로 바꾸기 
전체보기에서 정렬과 년/월/주/일별로 보기 추가
전체보기 출력 방식을 인스타처럼
전체보기 일별로 출력 시 자신이 선택한 영화의 분위기도 같이 출력
중복된 리뷰를 출력할 상세페이지 작성

유저 탭에서 각 행 클릭 시 출력될 상세페이지 만들기
유저 탭에서 질문 설정하기

목표 탭 만들어보기
목표 탭에 별에 따라 애니메이션 출력

일기 작성 버튼 위치 수정
일기 작성 화면에서 스크롤 수정
제목 입력 자동완성/미리보기 기능
평론을 빼고 영화의 분위기나 느낌을 선택할 수 있는 화면 만들기

닫기버튼 없는 화면 수정하기(저장이 필요한 페이지에서는 경고 버튼 띄우기)
