### ISSUE TITLE
1월 14일까지 각자 새로운 프로토타입 만들어 오기!!

### ISSUE THREAD

**Issue by zihos** [ProjectInTheClass/MovieDialog#19]

**Comment by PMinJoo** [comment]
https://drive.google.com/file/d/1T49pGIKhY8hYqsutgD7t6MPKfYApDlYK/view?usp=sharing

**Comment by zihos** [comment]
![img_4770](https://user-images.githubusercontent.com/46514182/51097534-3fc21600-1808-11e9-90c5-87af251190dd.JPG)
![img_4769](https://user-images.githubusercontent.com/46514182/51097536-3fc21600-1808-11e9-935e-daa0402291db.JPG)
![img_4768](https://user-images.githubusercontent.com/46514182/51097537-3fc21600-1808-11e9-9b6f-be20af8136c8.JPG)

**Comment by IMCHO** [comment]
https://drive.google.com/file/d/1afbPX7N9KF-I9kcUA394KmKg08LEaQnW/view?usp=sharing
